import fs from 'fs';
import path from 'path';

export function generateHtmlReport({ unusedJS, unusedCSS, unusedAssets }, outputPath = 'sweepy-report.html') {
  const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Sweepy Report</title>
  <style>
    body { font-family: sans-serif; padding: 2rem; background: #f9f9f9; }
    h1 { color: #f55; }
    h2 { margin-top: 2rem; }
    ul { background: #fff; padding: 1rem; border-radius: 6px; box-shadow: 0 2px 6px rgba(0,0,0,0.1); }
    li { margin: 0.25rem 0; font-family: monospace; }
  </style>
</head>
<body>
  <h1>🧹 Sweepy Report</h1>

  <h2>Unused JS/TS Files (${unusedJS.length})</h2>
  <ul>${unusedJS.map(file => `<li>${file}</li>`).join('')}</ul>

  <h2>Unused CSS/SCSS Files (${unusedCSS.length})</h2>
  <ul>${unusedCSS.map(file => `<li>${file}</li>`).join('')}</ul>

  <h2>Orphaned Assets (${unusedAssets.length})</h2>
  <ul>${unusedAssets.map(file => `<li>${file}</li>`).join('')}</ul>

  <p style="margin-top:2rem;color:#999">Generated by Sweepy</p>
</body>
</html>
  `;

  fs.writeFileSync(path.resolve(outputPath), html, 'utf-8');
}
